services:
  sanic:
    build: .
    env_file: .env
    ports:
      - 5000:5000
    restart: unless-stopped
  webserver:
    image: arm64v8/nginx:latest
    ports:
      - 80:80
      - 443:443
    restart: unless-stopped
    volumes:
      - ./data/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./frontend/dist/assets:/assets
      - ./data/certbot/conf:/etc/letsencrypt
      - .data/certbot/www:/var/www/certbot
    depends_on:
      - sanic
  certbot:
    image: certbot/certbot:arm64v8-latest
    volume:
      - ./data/certbot/conf:/etc/letsencrypt
      - .data/certbot/www:/var/www/certbot

networks:
  default:
    driver: bridge