version: '3.3'
services:
  sanic:
    container_name: webserver
    build: .
    env_file: .env
    ports:
      - 5000:5000
    restart: unless-stopped
  nginx:
    container_name: nginx
    image: arm64v8/nginx:latest
    ports:
      - 80:80
      - 443:443
    restart: unless-stopped
    volumes:
      - ./data/nginx.staging.conf:/etc/nginx/conf.d/default.conf
      - ./frontend/dist:/front
      - ./data/s3:/s3
    depends_on:
      - sanic
      - s3
  s3:
    container_name: s3
    image: minio/minio:latest
    restart: unless-stopped
    ports:
      - 9000:9000
      - 9090:9090
    volumes:
      - ./data/s3:/data
    env_file:
      - ./data/s3_env.env
    command: server /data --console-address ":9090"

networks:
  default:
    driver: bridge