services:
  sanic:
    build: .
    env_file: .env
    ports:
      - 5000:5000
    restart: unless-stopped
  nginx:
    image: arm64v8/nginx:latest
    ports:
      - 80:80
      - 443:443
    restart: unless-stopped
    volumes:
      - ./data/nginx.staging.conf:/etc/nginx/conf.d/default.conf
      - ./frontend/dist/assets:/assets
    depends_on:
      - sanic

networks:
  default:
    driver: bridge